[2022-02-09 20:31:41,768] {taskinstance.py:1026} INFO - Dependencies not met for <TaskInstance: green_taxi_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 0}, upstream_task_ids={'format_to_parquet_task'}
[2022-02-09 20:31:41,777] {local_task_job.py:99} INFO - Task is not able to be run
[2022-02-09 20:32:05,750] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-09 20:32:05,789] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: green_taxi_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-09 20:32:05,789] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 20:32:05,790] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-02-09 20:32:05,790] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-09 20:32:05,844] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 00:00:00+00:00
[2022-02-09 20:32:05,864] {standard_task_runner.py:52} INFO - Started process 165 to run task
[2022-02-09 20:32:05,889] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-01-02T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/green_gcs_dag.py', '--cfg-path', '/tmp/tmpf7lpizu4', '--error-file', '/tmp/tmpffk5z660']
[2022-02-09 20:32:05,895] {standard_task_runner.py:77} INFO - Job 28: Subtask local_to_gcs_task
[2022-02-09 20:32:06,060] {logging_mixin.py:109} INFO - Running <TaskInstance: green_taxi_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [running]> on host 4f97b6b16bdb
[2022-02-09 20:32:06,231] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-09 20:32:06,340] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T00:00:00+00:00
[2022-02-09 20:32:08,132] {python.py:175} INFO - Done. Returned value was: None
[2022-02-09 20:32:08,171] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=green_taxi_gcs_dag, task_id=local_to_gcs_task, execution_date=20190102T000000, start_date=20220209T203205, end_date=20220209T203208
[2022-02-09 20:32:08,271] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-09 20:32:08,364] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
