[2022-02-19 23:47:51,909] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-19 23:47:51,975] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-19 23:47:51,976] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:47:51,976] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-19 23:47:51,976] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:47:52,062] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2019-01-02 00:00:00+00:00
[2022-02-19 23:47:52,080] {standard_task_runner.py:52} INFO - Started process 761 to run task
[2022-02-19 23:47:52,108] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'format_to_parquet_task', 'scheduled__2019-01-02T00:00:00+00:00', '--job-id', '246', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmplqxy2sa7', '--error-file', '/tmp/tmpvpx2byo_']
[2022-02-19 23:47:52,111] {standard_task_runner.py:77} INFO - Job 246: Subtask format_to_parquet_task
[2022-02-19 23:47:52,499] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [running]> on host 812dd7ecce85
[2022-02-19 23:47:52,589] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-19 23:47:52,636] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T00:00:00+00:00
[2022-02-19 23:48:03,754] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fhv_gcs_dag.py", line 27, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 18 columns, got 7: 1,2019-01-16 06:54:44,2019-01-16 07:11:59,1,2.30,1,N
[2022-02-19 23:48:04,316] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=fhv_gcs_dag, task_id=format_to_parquet_task, execution_date=20190102T000000, start_date=20220219T234751, end_date=20220219T234804
[2022-02-19 23:48:04,750] {standard_task_runner.py:92} ERROR - Failed to execute job 246 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fhv_gcs_dag.py", line 27, in format_to_parquet
    table = pv.read_csv(src_file)
  File "pyarrow/_csv.pyx", line 867, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 876, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 18 columns, got 7: 1,2019-01-16 06:54:44,2019-01-16 07:11:59,1,2.30,1,N
[2022-02-19 23:48:05,230] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-19 23:48:06,904] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-23 19:32:57,152] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-23 19:32:57,166] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-23 19:32:57,166] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 19:32:57,166] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-23 19:32:57,166] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 19:32:57,184] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2019-01-02 00:00:00+00:00
[2022-02-23 19:32:57,190] {standard_task_runner.py:52} INFO - Started process 819 to run task
[2022-02-23 19:32:57,194] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'format_to_parquet_task', 'scheduled__2019-01-02T00:00:00+00:00', '--job-id', '651', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpg1u7gwvj', '--error-file', '/tmp/tmpsa17evgo']
[2022-02-23 19:32:57,195] {standard_task_runner.py:77} INFO - Job 651: Subtask format_to_parquet_task
[2022-02-23 19:32:57,250] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [running]> on host 537c9393f0b3
[2022-02-23 19:32:57,285] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 19:32:57,303] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T00:00:00+00:00
[2022-02-23 19:33:11,698] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2022-02-23 19:33:12,005] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=fhv_gcs_dag, task_id=format_to_parquet_task, execution_date=20190102T000000, start_date=20220223T193257, end_date=20220223T193312
[2022-02-23 19:33:12,125] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-23 20:49:48,868] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-23 20:49:48,882] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-23 20:49:48,883] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:49:48,883] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-23 20:49:48,883] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:49:48,911] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2019-01-02 00:00:00+00:00
[2022-02-23 20:49:48,917] {standard_task_runner.py:52} INFO - Started process 814 to run task
[2022-02-23 20:49:48,921] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'format_to_parquet_task', 'scheduled__2019-01-02T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmp5e1eazf2', '--error-file', '/tmp/tmprreh5j1m']
[2022-02-23 20:49:48,924] {standard_task_runner.py:77} INFO - Job 49: Subtask format_to_parquet_task
[2022-02-23 20:49:48,990] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.format_to_parquet_task scheduled__2019-01-02T00:00:00+00:00 [running]> on host 1c172e0325c8
[2022-02-23 20:49:49,036] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 20:49:49,058] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T00:00:00+00:00
[2022-02-23 20:50:07,242] {local_task_job.py:154} INFO - Task exited with return code Negsignal.SIGKILL
[2022-02-23 20:50:07,483] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=fhv_gcs_dag, task_id=format_to_parquet_task, execution_date=20190102T000000, start_date=20220223T204948, end_date=20220223T205007
[2022-02-23 20:50:07,695] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
